VALID_TICKERS = [
    "1INCH",
    "1MBABYDOGE",
    "A",
    "A2Z",
    "A8",
    "AAVE",
    "ACE",
    "ACH",
    "ACT",
    "ACX",
    "ADA",
    "AERGO",
    "AERO",
    "AEVO",
    "AGI",
    "AGLD",
    "AGT",
    "AI",
    "AI16Z",
    "AIN",
    "AIO",
    "AIOT",
    "AIOZ",
    "AIXBT",
    "AKT",
    "ALCH",
    "ALEO",
    "ALGO",
    "ALICE",
    "ALL",
    "ALPHA",
    "ALPINE",
    "ALT",
    "ALU",
    "ANIME",
    "ANKR",
    "APE",
    "APEX",
    "API3",
    "APT",
    "AR",
    "ARB",
    "ARC",
    "ARIA",
    "ARK",
    "ARKM",
    "ARPA",
    "ASP",
    "ASR",
    "ASTER",
    "ASTR",
    "ATA",
    "ATH",
    "ATOM",
    "AUCTION",
    "AUDIO",
    "AVA",
    "AVAAI",
    "AVAIL",
    "AVAX",
    "AVL",
    "AVNT",
    "AWE",
    "AXL",
    "AXS",
    "B",
    "B2",
    "B3",
    "BABY",
    "BADGER",
    "BAKE",
    "BAN",
    "BANANA",
    "BANANAS31",
    "BAND",
    "BANK",
    "BAS",
    "BAT",
    "BB",
    "BCH",
    "BDXN",
    "BEAMX",
    "BEL",
    "BERA",
    "BICO",
    "BID",
    "BIGTIME",
    "BIO",
    "BLAST",
    "BLUR",
    "BMT",
    "BNB",
    "BNT",
    "BOB",
    "BOBA",
    "BOME",
    "BONK",
    "BR",
    "BRETT",
    "BROCCOLI714",
    "BROCCOLIF3B",
    "BSU",
    "BSV",
    "BSW",
    "BTC",
    "BTR",
    "BTT",
    "BULLA",
    "C",
    "C98",
    "CAKE",
    "CAMP",
    "CARV",
    "CAT",
    "CATI",
    "CELO",
    "CELR",
    "CETUS",
    "CFX",
    "CGPT",
    "CHEEMS",
    "CHESS",
    "CHILLGUY",
    "CHR",
    "CHZ",
    "CKB",
    "CLANKER",
    "CLOUD",
    "COMP",
    "COOK",
    "COOKIE",
    "COQ",
    "CORE",
    "COS",
    "COTI",
    "COW",
    "CPOOL",
    "CRO",
    "CROSS",
    "CRV",
    "CTC",
    "CTK",
    "CTSI",
    "CUDIS",
    "CVC",
    "CVX",
    "CYBER",
    "D",
    "DAM",
    "DASH",
    "DBR",
    "DEEP",
    "DEGEN",
    "DEGO",
    "DENT",
    "DEXE",
    "DF",
    "DGB",
    "DIA",
    "DMC",
    "DODOX",
    "DOG",
    "DOGE",
    "DOGS",
    "DOLO",
    "DOOD",
    "DOT",
    "DRIFT",
    "DUCK",
    "DUSK",
    "DYDX",
    "DYM",
    "EDU",
    "EGLD",
    "EIGEN",
    "ELON",
    "ELX",
    "ENA",
    "ENJ",
    "ENS",
    "EPIC",
    "EPT",
    "ERA",
    "ES",
    "ESPORTS",
    "ETC",
    "ETH",
    "ETHFI",
    "ETHW",
    "F",
    "FARTCOIN",
    "FET",
    "FHE",
    "FIDA",
    "FIL",
    "FIO",
    "FIS",
    "FLM",
    "FLOCK",
    "FLOKI",
    "FLOW",
    "FLR",
    "FLUX",
    "FORM",
    "FORTH",
    "FRAG",
    "FUEL",
    "FUN",
    "FWOG",
    "FXS",
    "G",
    "GALA",
    "GAS",
    "GHST",
    "GIGA",
    "GLM",
    "GLMR",
    "GMT",
    "GMX",
    "GNO",
    "GOAT",
    "GODS",
    "GORK",
    "GPS",
    "GRASS",
    "GRIFFAIN",
    "GRT",
    "GTC",
    "GUN",
    "H",
    "HAEDAL",
    "HBAR",
    "HEI",
    "HEMI",
    "HFT",
    "HIFI",
    "HIGH",
    "HIPPO",
    "HIVE",
    "HMSTR",
    "HNT",
    "HOME",
    "HOOK",
    "HOT",
    "HPOS10I",
    "HUMA",
    "HYPE",
    "HYPER",
    "ICNT",
    "ICP",
    "ICX",
    "ID",
    "IDEX",
    "IDOL",
    "ILV",
    "IMX",
    "IN",
    "INIT",
    "INJ",
    "IO",
    "IOST",
    "IOTA",
    "IOTX",
    "IP",
    "J",
    "JASMY",
    "JELLYJELLY",
    "JOE",
    "JST",
    "JTO",
    "JUP",
    "K",
    "KAIA",
    "KAITO",
    "KAS",
    "KAVA",
    "KDA",
    "KERNEL",
    "KMNO",
    "KNC",
    "KOMA",
    "KSM",
    "L3",
    "LA",
    "LADYS",
    "LAUNCHCOIN",
    "LAYER",
    "LDO",
    "LINEA",
    "LINK",
    "LISTA",
    "LOOKS",
    "LPT",
    "LQTY",
    "LRC",
    "LSK",
    "LTC",
    "LUMIA",
    "LUNA2",
    "LUNC",
    "M",
    "MAGIC",
    "MAJOR",
    "MANA",
    "MANTA",
    "MASA",
    "MASK",
    "MAV",
    "MAVIA",
    "MBOX",
    "ME",
    "MEGA",
    "MELANIA",
    "MEME",
    "MERL",
    "METIS",
    "MET",
    "MEW",
    "MILK",
    "MINA",
    "MITO",
    "MLN",
    "MNT",
    "MOCA",
    "MOG",
    "MON",
    "MOODENG",
    "MORPHO",
    "MOVE",
    "MOVR",
    "MTL",
    "MUBARAK",
    "MVL",
    "MYRIA",
    "MYRO",
    "MYX",
    "NAORIS",
    "NEAR",
    "NEIRO",
    "NEO",
    "NEWT",
    "NFP",
    "NIL",
    "NKN",
    "NMR",
    "NODE",
    "NOT",
    "NS",
    "NTRN",
    "NXPC",
    "OBOL",
    "OBT",
    "OG",
    "OGN",
    "OL",
    "OM",
    "OMNI",
    "ONDO",
    "ONE",
    "ONG",
    "ONT",
    "OP",
    "OPEN",
    "ORBS",
    "ORCA",
    "ORDER",
    "ORDI",
    "OSMO",
    "OXT",
    "PARTI",
    "PAXG",
    "PEAQ",
    "PEIPEI",
    "PENDLE",
    "PENGU",
    "PEOPLE",
    "PEPE",
    "PERP",
    "PHA",
    "PHB",
    "PIPPIN",
    "PIXEL",
    "XPL",
    "PLAY",
    "PLUME",
    "PNUT",
    "POL",
    "POLYX",
    "PONKE",
    "POPCAT",
    "PORT3",
    "PORTAL",
    "POWR",
    "PRCL",
    "PRIME",
    "PROM",
    "PROMPT",
    "PROVE",
    "PTB",
    "PUFFER",
    "PUMP",
    "PUMPBTC",
    "PUNDIX",
    "PYR",
    "PYTH",
    "Q",
    "QI",
    "QNT",
    "QTUM",
    "QUBIC",
    "QUICK",
    "RAD",
    "RARE",
    "RATS",
    "RAYSOL",
    "RDNT",
    "RED",
    "REI",
    "RENDER",
    "REQ",
    "RESOLV",
    "REX",
    "REZ",
    "RFC",
    "RHEA",
    "RIF",
    "RLC",
    "ROAM",
    "RONIN",
    "ROSE",
    "RPL",
    "RSR",
    "RSS3",
    "RUNE",
    "RVN",
    "S",
    "SAFE",
    "SAGA",
    "SAHARA",
    "SAND",
    "SANTOS",
    "SAPIEN",
    "SAROS",
    "SATS",
    "SC",
    "SCA",
    "SCR",
    "SCRT",
    "SD",
    "SEI",
    "SEND",
    "SERAPH",
    "SFP",
    "SHELL",
    "SHIB",
    "SIGN",
    "SIREN",
    "SKATE",
    "SKL",
    "SKY",
    "SKYAI",
    "SLERF",
    "SLF",
    "SLP",
    "SNT",
    "SNX",
    "SOL",
    "SOLO",
    "SOLV",
    "SOMI",
    "SONIC",
    "SOON",
    "SOPH",
    "SOSO",
    "SPEC",
    "SPELL",
    "SPK",
    "SPX",
    "SQD",
    "SSV",
    "STEEM",
    "STG",
    "STO",
    "STORJ",
    "STRK",
    "STX",
    "STBL",
    "SUI",
    "SUN",
    "SUNDOG",
    "SUPER",
    "SUSHI",
    "SWARMS",
    "SWEAT",
    "SWELL",
    "SXP",
    "SXT",
    "SYN",
    "SYRUP",
    "SYS",
    "T",
    "TA",
    "TAC",
    "TAG",
    "TAI",
    "TAIKO",
    "TAKE",
    "TANSSI",
    "TAO",
    "THE",
    "THETA",
    "TIA",
    "TLM",
    "TNSR",
    "TOKEN",
    "TON",
    "TOSHI",
    "TOWNS",
    "TRB",
    "TREE",
    "TRU",
    "TRUMP",
    "TRX",
    "TST",
    "TURBO",
    "TUT",
    "TWT",
    "UMA",
    "UNI",
    "USD1",
    "USDE",
    "USELESS",
    "USTC",
    "USUAL",
    "UXLINK",
    "VANA",
    "VANRY",
    "VELO",
    "VELODROME",
    "VELVET",
    "VET",
    "VIC",
    "VINE",
    "VIRTUAL",
    "VOXEL",
    "VR",
    "VTHO",
    "VVV",
    "W",
    "WAL",
    "WAVES",
    "WAXP",
    "WCT",
    "WEN",
    "WHY",
    "WIF",
    "WLD",
    "WLFI",
    "WOO",
    "X",
    "XAI",
    "XAUT",
    "XCH",
    "XCN",
    "XDC",
    "XEC",
    "XEM",
    "XION",
    "XLM",
    "XMR",
    "XNO",
    "XNY",
    "XPL",
    "XRP",
    "XTER",
    "XTZ",
    "XVG",
    "XVS",
    "YALA",
    "YFI",
    "YGG",
    "YZY",
    "ZBCN",
    "ZEC",
    "ZEN",
    "ZENT",
    "ZEREBRO",
    "ZETA",
    "ZEUS",
    "ZIL",
    "ZK",
    "ZKJ",
    "ZORA",
    "ZRC",
    "ZRO",
    "ZRX",
]

UI_TIKCERS = [
    "1inch - 1INCH",
    "Baby Doge Coin - 1MBABYDOGE",
    "Vaulta - A",
    "Arena-Z - A2Z",
    "Ancient8 - A8",
    "Aave - AAVE",
    "Fusionist - ACE",
    "Alchemy Pay - ACH",
    "Act I : The AI Prophecy - ACT",
    "Across Protocol - ACX",
    "Cardano - ADA",
    "Aergo - AERGO",
    "Aerodrome Finance - AERO",
    "Aevo - AEVO",
    "Delysium - AGI",
    "Adventure Gold - AGLD",
    "Alaya Governance Token - AGT",
    "Sleepless AI - AI",
    "ai16z - AI16Z",
    "Infinity Ground - AIN",
    "OLAXBT - AIO",
    "OKZOO - AIOT",
    "AIOZ Network - AIOZ",
    "aixbt - AIXBT",
    "Akash Network - AKT",
    "Alchemist AI - ALCH",
    "Aleo - ALEO",
    "Algorand - ALGO",
    "MyNeighborAlice - ALICE",
    "Binance ALL Composite Index - ALL",
    "Stella - ALPHA",
    "Alpine F1 Team Fan Token - ALPINE",
    "Altlayer - ALT",
    "Altura - ALU",
    "Animecoin - ANIME",
    "Ankr - ANKR",
    "ApeCoin - APE",
    "ApeX Protocol - APEX",
    "API3 - API3",
    "Aptos - APT",
    "Arweave - AR",
    "Arbitrum - ARB",
    "AI Rig Complex - ARC",
    "AriaAI - ARIA",
    "Ark - ARK",
    "Arkham - ARKM",
    "ARPA - ARPA",
    "Aspecta - ASP",
    "AS Roma Fan Token - ASR",
    "Aster - ASTER",
    "Astar - ASTR",
    "Automata Network - ATA",
    "Aethir - ATH",
    "Cosmos - ATOM",
    "Bounce Token - AUCTION",
    "Audius - AUDIO",
    "AVA (Travala) - AVA",
    "avaai.top - AVAAI",
    "Avail - AVAIL",
    "Avalanche - AVAX",
    "Avalon Labs (AVL) - AVL",
    "Avantis - AVNT",
    "AWE - AWE",
    "Axelar - AXL",
    "Axie Infinity - AXS",
    "BUILDon - B",
    "BSquared Network - B2",
    "B3 (Base) - B3",
    "Babylon - BABY",
    "Badger DAO - BADGER",
    "BakeryToken - BAKE",
    "Comedian - BAN",
    "Banana Gun - BANANA",
    "Banana For Scale - BANANAS31",
    "Band - BAND",
    "Lorenzo Protocol - BANK",
    "BNB Attestation Service - BAS",
    "Basic Attention Token - BAT",
    "BounceBit - BB",
    "Bitcoin Cash - BCH",
    "BONDEX - BDXN",
    "Beam - BEAMX",
    "Bella Protocol - BEL",
    "Berachain - BERA",
    "Biconomy - BICO",
    "CreatorBid - BID",
    "Big Time - BIGTIME",
    "Bio Protocol - BIO",
    "Blast - BLAST",
    "Blur - BLUR",
    "Bubblemaps - BMT",
    "BNB - BNB",
    "Bancor - BNT",
    "Build On BNB - BOB",
    "Boba Network - BOBA",
    "BOOK OF MEME - BOME",
    "Bonk - BONK",
    "Bedrock - BR",
    "Brett (Based) - BRETT",
    "CZ's Dog - BROCCOLI714",
    "Broccoli (firstbroccoli.com) - BROCCOLIF3B",
    "Baby Shark Universe - BSU",
    "Bitcoin SV - BSV",
    "Biswap - BSW",
    "Bitcoin - BTC",
    "Bitlayer - BTR",
    "BitTorrent [New] - BTT",
    "Bulla - BULLA",
    "Chainbase - C",
    "Coin98 - C98",
    "PancakeSwap - CAKE",
    "Camp Network - CAMP",
    "CARV - CARV",
    "Simon's Cat - CAT",
    "Catizen - CATI",
    "Celo - CELO",
    "Celer Network - CELR",
    "Cetus Protocol - CETUS",
    "Conflux - CFX",
    "ChainGPT - CGPT",
    "Cheems (cheems.pet) - CHEEMS",
    "Tranchess - CHESS",
    "Just a chill guy - CHILLGUY",
    "Chromia - CHR",
    "Chiliz - CHZ",
    "Nervos Network - CKB",
    "tokenbot - CLANKER",
    "Cloud - CLOUD",
    "Compound - COMP",
    "mETH Protocol - COOK",
    "Cookie DAO - COOKIE",
    "Coq Inu - COQ",
    "Core - CORE",
    "Contentos - COS",
    "COTI - COTI",
    "CoW Protocol - COW",
    "Clearpool - CPOOL",
    "Cronos - CRO",
    "CROSS - CROSS",
    "Curve DAO Token - CRV",
    "Creditcoin - CTC",
    "Shentu - CTK",
    "Cartesi - CTSI",
    "CUDIS - CUDIS",
    "Civic - CVC",
    "Convex Finance - CVX",
    "Cyber - CYBER",
    "DAR Open Network - D",
    "Reservoir - DAM",
    "Dash - DASH",
    "deBridge - DBR",
    "DeepBook Protocol - DEEP",
    "Degen - DEGEN",
    "Dego Finance - DEGO",
    "Dent - DENT",
    "DeXe - DEXE",
    "dForce - DF",
    "DigiByte - DGB",
    "DIA - DIA",
    "DeLorean - DMC",
    "DODO - DODOX",
    "Dog (Bitcoin) - DOG",
    "Dogecoin - DOGE",
    "DOGS - DOGS",
    "Dolomite - DOLO",
    "Doodles - DOOD",
    "Polkadot - DOT",
    "Drift - DRIFT",
    "DuckChain - DUCK",
    "Dusk - DUSK",
    "dYdX (ethDYDX) - DYDX",
    "Dymension - DYM",
    "Open Campus - EDU",
    "MultiversX - EGLD",
    "EigenLayer - EIGEN",
    "Dogelon Mars - ELON",
    "Elixir - ELX",
    "Ethena - ENA",
    "Enjin Coin - ENJ",
    "Ethereum Name Service - ENS",
    "Epic Chain - EPIC",
    "Balance - EPT",
    "Caldera - ERA",
    "Eclipse - ES",
    "Yooldo - ESPORTS",
    "Ethereum Classic - ETC",
    "Ethereum - ETH",
    "ether.fi - ETHFI",
    "EthereumPoW - ETHW",
    "SynFutures - F",
    "Fartcoin - FARTCOIN",
    "Artificial Superintelligence Alliance - FET",
    "Mind Network - FHE",
    "Bonfida (aka SNS) - FIDA",
    "Filecoin - FIL",
    "FIO Protocol - FIO",
    "StaFi - FIS",
    "Flamingo - FLM",
    "FLock.io - FLOCK",
    "FLOKI - FLOKI",
    "Flow - FLOW",
    "Flare - FLR",
    "Flux - FLUX",
    "Four - FORM",
    "Ampleforth Governance Token - FORTH",
    "Fragmetric - FRAG",
    "Fuel Network - FUEL",
    "FUNToken - FUN",
    "Fwog (SOL) - FWOG",
    "Frax (prev. FXS) - FXS",
    "Gravity (by Galxe) - G",
    "Gala - GALA",
    "Gas - GAS",
    "Aavegotchi - GHST",
    "Gigachad - GIGA",
    "Golem - GLM",
    "Moonbeam - GLMR",
    "GMT - GMT",
    "GMX - GMX",
    "Gnosis - GNO",
    "Goatseus Maximus - GOAT",
    "Gods Unchained - GODS",
    "New XAI gork - GORK",
    "GoPlus Security - GPS",
    "Grass - GRASS",
    "GRIFFAIN - GRIFFAIN",
    "The Graph - GRT",
    "Gitcoin - GTC",
    "GUNZ - GUN",
    "Humanity Protocol - H",
    "Haedal Protocol - HAEDAL",
    "Hedera - HBAR",
    "Heima - HEI",
    "Hemi - HEMI",
    "Hashflow - HFT",
    "Hifi Finance - HIFI",
    "Highstreet - HIGH",
    "sudeng - HIPPO",
    "Hive - HIVE",
    "Hamster Kombat - HMSTR",
    "Helium - HNT",
    "Defi App - HOME",
    "Hooked Protocol - HOOK",
    "Holo - HOT",
    "HarryPotterObamaSonic10Inu (ERC-20) - HPOS10I",
    "Huma Finance - HUMA",
    "Hyperliquid - HYPE",
    "Hyperlane - HYPER",
    "Impossible Cloud Network - ICNT",
    "Internet Computer - ICP",
    "ICON - ICX",
    "SPACE ID - ID",
    "IDEX - IDEX",
    "MEET48 - IDOL",
    "Illuvium - ILV",
    "Immutable - IMX",
    "INFINIT - IN",
    "Initia - INIT",
    "Injective - INJ",
    "io.net - IO",
    "IOST - IOST",
    "IOTA - IOTA",
    "IoTeX - IOTX",
    "Story - IP",
    "Jambo - J",
    "JasmyCoin - JASMY",
    "Jelly-My-Jelly - JELLYJELLY",
    "JOE - JOE",
    "JUST - JST",
    "Jito - JTO",
    "Jupiter - JUP",
    "Sidekick - K",
    "Kaia - KAIA",
    "KAITO - KAITO",
    "Kaspa - KAS",
    "Kava - KAVA",
    "Kadena - KDA",
    "KernelDAO - KERNEL",
    "Kamino Finance - KMNO",
    "Kyber Network Crystal v2 - KNC",
    "Koma Inu - KOMA",
    "Kusama - KSM",
    "Layer3 - L3",
    "Lagrange - LA",
    "Milady Meme Coin - LADYS",
    "Launch Coin on Believe - LAUNCHCOIN",
    "Solayer - LAYER",
    "Lido DAO - LDO",
    "Linea - LINEA",
    "Chainlink - LINK",
    "Lista DAO - LISTA",
    "LooksRare - LOOKS",
    "Livepeer - LPT",
    "Liquity - LQTY",
    "Loopring - LRC",
    "Lisk - LSK",
    "Litecoin - LTC",
    "Lumia - LUMIA",
    "Terra - LUNA2",
    "Terra Classic - LUNC",
    "MemeCore - M",
    "Treasure - MAGIC",
    "Major - MAJOR",
    "Decentraland - MANA",
    "Manta Network - MANTA",
    "Masa - MASA",
    "Mask Network - MASK",
    "Maverick Protocol - MAV",
    "Heroes of Mavia - MAVIA",
    "MOBOX - MBOX",
    "Magic Eden - ME",
    "MegaETH - MEGA",
    "Official Melania Meme - MELANIA",
    "Memecoin - MEME",
    "Merlin Chain - MERL",
    "Metis - METIS",
    "Meteora - MET",
    "cat in a dogs world - MEW",
    "MilkyWay - MILK",
    "Mina - MINA",
    "Mitosis - MITO",
    "Enzyme - MLN",
    "Mantle - MNT",
    "Moca Network - MOCA",
    "Mog Coin - MOG",
    "Monad - MON",
    "Moo Deng (moodengsol.com) - MOODENG",
    "Morpho - MORPHO",
    "Movement - MOVE",
    "Moonriver - MOVR",
    "Metal DAO - MTL",
    "Mubarak - MUBARAK",
    "MVL - MVL",
    "Myria - MYRIA",
    "Myro - MYRO",
    "MYX Finance - MYX",
    "Naoris Protocol - NAORIS",
    "NEAR Protocol - NEAR",
    "Neiro (First Neiro On Ethereum) - NEIRO",
    "Neo - NEO",
    "Newton Protocol - NEWT",
    "NFPrompt - NFP",
    "Nillion - NIL",
    "NKN - NKN",
    "Numeraire - NMR",
    "NodeOps - NODE",
    "Notcoin - NOT",
    "Sui Name Service - NS",
    "Neutron - NTRN",
    "NEXPACE - NXPC",
    "Obol - OBOL",
    "Orbiter Finance - OBT",
    "OG Fan Token - OG",
    "Origin Protocol - OGN",
    "Open Loot - OL",
    "MANTRA - OM",
    "Omni Network - OMNI",
    "Ondo - ONDO",
    "Harmony - ONE",
    "Ontology Gas - ONG",
    "Ontology - ONT",
    "Optimism - OP",
    "OpenLedger - OPEN",
    "Orbs - ORBS",
    "Orca - ORCA",
    "Orderly - ORDER",
    "ORDI - ORDI",
    "Osmosis - OSMO",
    "Orchid - OXT",
    "Particle Network - PARTI",
    "PAX Gold - PAXG",
    "peaq - PEAQ",
    "PeiPei (ETH) - PEIPEI",
    "Pendle - PENDLE",
    "Pudgy Penguins - PENGU",
    "ConstitutionDAO - PEOPLE",
    "Pepe - PEPE",
    "Perpetual Protocol - PERP",
    "Phala Network - PHA",
    "Phoenix - PHB",
    "pippin - PIPPIN",
    "Pixels - PIXEL",
    "Plasma - XPL",
    "PlaysOut - PLAY",
    "Plume - PLUME",
    "Peanut the Squirrel - PNUT",
    "POL (prev. MATIC) - POL",
    "Polymesh - POLYX",
    "Ponke - PONKE",
    "Popcat (SOL) - POPCAT",
    "Port3 Network - PORT3",
    "Portal - PORTAL",
    "Powerledger - POWR",
    "Parcl - PRCL",
    "Echelon Prime - PRIME",
    "Prom - PROM",
    "Wayfinder - PROMPT",
    "Succinct - PROVE",
    "Portal To Bitcoin - PTB",
    "Puffer - PUFFER",
    "Pump.fun - PUMP",
    "PumpBTC (Governance token) - PUMPBTC",
    "Pundi X (New) - PUNDIX",
    "Vulcan Forged (PYR) - PYR",
    "Pyth Network - PYTH",
    "Quack AI - Q",
    "BENQI - QI",
    "Quant - QNT",
    "Qtum - QTUM",
    "Qubic - QUBIC",
    "Quickswap [New] - QUICK",
    "Radworks - RAD",
    "SuperRare - RARE",
    "rats (Ordinals) - RATS",
    "Raydium - RAYSOL",
    "Radiant Capital - RDNT",
    "RedStone - RED",
    "REI Network - REI",
    "Render - RENDER",
    "Request - REQ",
    "Resolv - RESOLV",
    "REVOX - REX",
    "Renzo - REZ",
    "Retard Finder Coin - RFC",
    "RHEA Finance - RHEA",
    "Rootstock Infrastructure Framework - RIF",
    "iExec RLC - RLC",
    "Roam - ROAM",
    "Ronin - RONIN",
    "Oasis - ROSE",
    "Rocket Pool - RPL",
    "Reserve Rights - RSR",
    "RSS3 - RSS3",
    "THORChain - RUNE",
    "Ravencoin - RVN",
    "Sonic - S",
    "Safe - SAFE",
    "Saga - SAGA",
    "Sahara AI - SAHARA",
    "The Sandbox - SAND",
    "Santos FC Fan Token - SANTOS",
    "Sapien - SAPIEN",
    "Saros - SAROS",
    "SATS (Ordinals) - SATS",
    "Siacoin - SC",
    "Scallop - SCA",
    "Scroll - SCR",
    "Secret - SCRT",
    "Stader - SD",
    "Sei - SEI",
    "Suilend - SEND",
    "Seraph - SERAPH",
    "SafePal - SFP",
    "MyShell - SHELL",
    "Shiba Inu - SHIB",
    "Sign - SIGN",
    "siren - SIREN",
    "Skate - SKATE",
    "SKALE - SKL",
    "Sky - SKY",
    "SKYAI - SKYAI",
    "SLERF - SLERF",
    "Self Chain - SLF",
    "Smooth Love Potion - SLP",
    "Status - SNT",
    "Synthetix - SNX",
    "Solana - SOL",
    "Sologenic - SOLO",
    "Solv Protocol - SOLV",
    "Somnia - SOMI",
    "Sonic SVM - SONIC",
    "SOON - SOON",
    "Sophon - SOPH",
    "SoSoValue - SOSO",
    "Spectral - SPEC",
    "Spell Token - SPELL",
    "Spark - SPK",
    "SPX6900 - SPX",
    "Subsquid - SQD",
    "ssv.network - SSV",
    "Steem - STEEM",
    "Stargate Finance - STG",
    "StakeStone - STO",
    "Storj - STORJ",
    "Starknet - STRK",
    "Stacks - STX",
    "STBL - STBL",
    "Sui - SUI",
    "Sun [New] - SUN",
    "SUNDOG - SUNDOG",
    "SuperVerse - SUPER",
    "SushiSwap - SUSHI",
    "Swarms - SWARMS",
    "SWEAT - SWEAT",
    "Swell Network - SWELL",
    "Solar - SXP",
    "Space and Time - SXT",
    "Synapse - SYN",
    "Maple Finance - SYRUP",
    "Syscoin - SYS",
    "Threshold - T",
    "Trusta.AI - TA",
    "TAC Protocol - TAC",
    "Tagger - TAG",
    "TARS AI - TAI",
    "Taiko - TAIKO",
    "OVERTAKE - TAKE",
    "Tanssi - TANSSI",
    "Bittensor - TAO",
    "THENA - THE",
    "Theta Network - THETA",
    "Celestia - TIA",
    "Alien Worlds - TLM",
    "Tensor - TNSR",
    "TokenFi - TOKEN",
    "Toncoin - TON",
    "Toshi - TOSHI",
    "Towns - TOWNS",
    "Tellor - TRB",
    "Treehouse - TREE",
    "TrueFi - TRU",
    "OFFICIAL TRUMP - TRUMP",
    "TRON - TRX",
    "Test - TST",
    "Turbo - TURBO",
    "Tutorial - TUT",
    "Trust Wallet Token - TWT",
    "UMA - UMA",
    "Uniswap - UNI",
    "World Liberty Financial USD - USD1",
    "Ethena USDe - USDE",
    "Useless Coin - USELESS",
    "TerraClassicUSD - USTC",
    "Usual - USUAL",
    "UXLINK - UXLINK",
    "Vana - VANA",
    "Vanar Chain - VANRY",
    "Velo - VELO",
    "Velodrome Finance - VELODROME",
    "Velvet - VELVET",
    "VeChain - VET",
    "Viction - VIC",
    "Vine Coin - VINE",
    "Virtuals Protocol - VIRTUAL",
    "Voxies - VOXEL",
    "Victoria VR - VR",
    "VeThor Token - VTHO",
    "Venice Token - VVV",
    "Wormhole - W",
    "Walrus - WAL",
    "Waves - WAVES",
    "WAX - WAXP",
    "WalletConnect Token - WCT",
    "Wen - WEN",
    "WHY - WHY",
    "dogwifhat - WIF",
    "Worldcoin - WLD",
    "World Liberty Financial - WLFI",
    "WOO - WOO",
    "X Empire - X",
    "Xai - XAI",
    "Tether Gold - XAUT",
    "Chia - XCH",
    "Onyxcoin - XCN",
    "XDC Network - XDC",
    "eCash - XEC",
    "NEM - XEM",
    "XION - XION",
    "Stellar - XLM",
    "Monero - XMR",
    "Nano - XNO",
    "Codatta - XNY",
    "Plasma - XPL",
    "XRP - XRP",
    "Xterio - XTER",
    "Tezos - XTZ",
    "Verge - XVG",
    "Venus - XVS",
    "Yala - YALA",
    "yearn.finance - YFI",
    "Yield Guild Games - YGG",
    "YZY MONEY - YZY",
    "Zebec Network - ZBCN",
    "Zcash - ZEC",
    "Horizen - ZEN",
    "Zentry - ZENT",
    "Zerebro - ZEREBRO",
    "ZetaChain - ZETA",
    "Zeus Network - ZEUS",
    "Zilliqa - ZIL",
    "ZKsync - ZK",
    "Polyhedra Network - ZKJ",
    "ZORA - ZORA",
    "Zircuit - ZRC",
    "LayerZero - ZRO",
    "0x Protocol - ZRX",
]
